### ISSUE TITLE
Unable to run Ace Link on Apple M1 with v2.0.2 

### ISSUE THREAD

**Issue by Art-auto** [blaise-io/acelink#51] opened 2022-05-04 20:03 UTC
**Describe the bug**  
Ace Link does not respond after I try to open the AceStream link

**What I expected to happen**  
Ace Link runs fine

**Additional debug info**  
Docker settings: 
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": true
  }
}

Docker Desktop 4.7.1 (77678) 
MacBook Pro 2020 M1
MacOS Monterey 12.3.1 (21E258)
Logs from docker:

acelink--ace-stream-server
[blaiseio/acelink:2.0.2](https://github.com/blaise-io/acelink/issues/new?assignees=blaise-io&labels=bug&template=bug_report.md&title=)
RUNNING
2022-05-04 19:54:33,920|MainThread|acestream|init segmenter done: log_path=/root/.ACEStream/logs/segmenter.log
2022-05-04 19:54:33,927|MainThread|acestream|platform=linux
2022-05-04 19:54:33,929|MainThread|acestream|app=acestream
2022-05-04 19:54:33,929|MainThread|acestream|version=3.1.49 code=3014900 revision=dc5eac3 date=2019-07-15
2022-05-04 19:54:33,931|MainThread|acestream|use_local_db=True
2022-05-04 19:54:33,933|MainThread|acestream|use_m2crypto=True
2022-05-04 19:54:33,934|MainThread|acestream|is_gui_mode=0
2022-05-04 19:54:33,937|MainThread|acestream|enable debug: 0
2022-05-04 19:54:33,960|MainThread|acestream|get_default_api_version: 2
2022-05-04 19:54:33,963|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2022-05-04 19:54:33,965|MainThread|acestream.coreapp|state_dir=u'/root/.ACEStream'
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
2022-05-04 19:54:35,632|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2022-05-04 19:54:35,638|MainThread|acestream|enable debug: 0
2022-05-04 19:54:35,685|MainThread|acestream.coreapp|cannot load session config, use default
2022-05-04 19:54:35,942|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:35224
2022-05-04 19:54:35,944|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2022-05-04 19:54:35,945|MainThread|acestream.LM|listen on 8621
2022-05-04 19:54:35,947|MainThread|acestream.localdb|No existing database found. Attempting to creating a new database u'/root/.ACEStream/sqlite/torrentstream.sdb'
2022-05-04 19:54:36,102|AceStreamCoreThread|acestream.SocketHandler.SocketHandler|create_multicast_sockets: failed to create socket: ip=239.255.17.18 port=32968 local=172.17.0.2
Traceback (most recent call last):
  File "ACEStream/Core/BitTornado/SocketHandler.py", line 842, in create_multicast_sockets
  File "ACEStream/Core/BitTornado/SocketHandler.py", line 860, in create_single_multicast_socket
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 92] Protocol not available
2022-05-04 19:54:36,130|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=1 allow_intranet=1
2022-05-04 19:54:38,422|MainThread|acestream.coreapp|failed to start aircast manager
Traceback (most recent call last):
  File "core.c", line 1483, in 
  File "core.c", line 122, in 
  File "core.c", line 290, in 
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 1400, in __init__
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 1437, in _init_sockets
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 92] Protocol not available
2022-05-04 19:54:38,446|ServiceTaskQueueThread-2|acestream.Session|sync_time: no response
2022-05-04 19:54:38,474|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:51168
2022-05-04 19:54:38,476|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2022-05-04 19:54:38,478|Instance2InstanceThread-39|acestream.APIServer|run: ready to receive remote commands on 62062
2022-05-04 19:54:53,981|Thread-27|acestream.LiveDownloadImpl.7607b92456dfb05b057ba3749d4d8e2cf8ddc73c|update_manifest: got http error: code=500 msg=<urlopen error [Errno -3] Temporary failure in name resolution>
Exception in thread ZeroconfThread-31:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 849, in run
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 1452, in _periodic_check
AttributeError: 'Zeroconf' object has no attribute 'last_sockets_check'
2022-05-04 19:59:02,908|Thread-88|acestream.LiveDownloadImpl.7607b92456dfb05b057ba3749d4d8e2cf8ddc73c|update_manifest: got http error: code=500 msg=<urlopen error [Errno -2] Name or service not known>

**Comment by xavirg** [comment] 2022-08-14 16:55
Duplicate of https://github.com/blaise-io/acelink/issues/32

**Comment by FelikZ** [comment] 2022-12-18 11:16
Works for me:
M1 Macbook Pro + 2.0.2 (even with Virtualization Framework enabled) 

@Art-auto the error you have is fine, this is related to the stream itself, not the app.

**Comment by gorrinhojr** [comment] 2023-02-28 00:12
Same issue here. No idea on how to fix it.

**Comment by Swift-Jr** [comment] 2023-03-16 19:09
Same problem. This worked fine for me last year, this year doesn't seem to be working (Ventura 13.2 (22D49))

Streams are known to be working, but I always get the same issue
`2023-03-16 19:08:22 2023-03-16 19:08:22,671|MainThread|acestream|init segmenter done: log_path=/root/.ACEStream/logs/segmenter.log
2023-03-16 19:08:22 2023-03-16 19:08:22,674|MainThread|acestream|platform=linux
2023-03-16 19:08:22 2023-03-16 19:08:22,675|MainThread|acestream|app=acestream
2023-03-16 19:08:22 2023-03-16 19:08:22,675|MainThread|acestream|version=3.1.49 code=3014900 revision=dc5eac3 date=2019-07-15
2023-03-16 19:08:22 2023-03-16 19:08:22,675|MainThread|acestream|use_local_db=True
2023-03-16 19:08:22 2023-03-16 19:08:22,676|MainThread|acestream|use_m2crypto=True
2023-03-16 19:08:22 2023-03-16 19:08:22,676|MainThread|acestream|is_gui_mode=0
2023-03-16 19:08:22 2023-03-16 19:08:22,677|MainThread|acestream|enable debug: 0
2023-03-16 19:08:22 2023-03-16 19:08:22,688|MainThread|acestream|get_default_api_version: 2
2023-03-16 19:08:22 2023-03-16 19:08:22,689|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2023-03-16 19:08:22 2023-03-16 19:08:22,689|MainThread|acestream.coreapp|state_dir=u'/root/.ACEStream'
2023-03-16 19:08:22 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:22 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:22 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:22 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:22 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:22 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:22 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 ls: cannot access '/dev/disk/by-id/': No such file or directory
2023-03-16 19:08:23 2023-03-16 19:08:23,770|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2023-03-16 19:08:23 2023-03-16 19:08:23,774|MainThread|acestream|enable debug: 0
2023-03-16 19:08:23 2023-03-16 19:08:23,799|MainThread|acestream.coreapp|cannot load session config, use default
2023-03-16 19:08:23 2023-03-16 19:08:23,949|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:47788
2023-03-16 19:08:23 2023-03-16 19:08:23,950|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2023-03-16 19:08:23 2023-03-16 19:08:23,951|MainThread|acestream.LM|listen on 8621
2023-03-16 19:08:23 2023-03-16 19:08:23,952|MainThread|acestream.localdb|No existing database found. Attempting to creating a new database u'/root/.ACEStream/sqlite/torrentstream.sdb'
2023-03-16 19:08:24 2023-03-16 19:08:24,036|AceStreamCoreThread|acestream.SocketHandler.SocketHandler|create_multicast_sockets: failed to create socket: ip=239.255.17.18 port=32968 local=172.17.0.2
2023-03-16 19:08:24 Traceback (most recent call last):
2023-03-16 19:08:24   File "ACEStream/Core/BitTornado/SocketHandler.py", line 842, in create_multicast_sockets
2023-03-16 19:08:24   File "ACEStream/Core/BitTornado/SocketHandler.py", line 860, in create_single_multicast_socket
2023-03-16 19:08:24   File "/usr/lib/python2.7/socket.py", line 228, in meth
2023-03-16 19:08:24     return getattr(self._sock,name)(*args)
2023-03-16 19:08:24 error: [Errno 92] Protocol not available
2023-03-16 19:08:24 2023-03-16 19:08:24,051|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=1 allow_intranet=1
2023-03-16 19:08:25 2023-03-16 19:08:25,123|MainThread|acestream.coreapp|failed to start aircast manager
2023-03-16 19:08:25 Traceback (most recent call last):
2023-03-16 19:08:25   File "core.c", line 1483, in 
2023-03-16 19:08:25   File "core.c", line 122, in 
2023-03-16 19:08:25   File "core.c", line 290, in 
2023-03-16 19:08:25   File "ACEStream/third_party/zeroconf/zeroconf.py", line 1400, in __init__
2023-03-16 19:08:25   File "ACEStream/third_party/zeroconf/zeroconf.py", line 1437, in _init_sockets
2023-03-16 19:08:25   File "/usr/lib/python2.7/socket.py", line 228, in meth
2023-03-16 19:08:25     return getattr(self._sock,name)(*args)
2023-03-16 19:08:25 error: [Errno 92] Protocol not available
2023-03-16 19:08:25 2023-03-16 19:08:25,141|ServiceTaskQueueThread-2|acestream.Session|sync_time: no response
2023-03-16 19:08:25 2023-03-16 19:08:25,147|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:35605
2023-03-16 19:08:25 2023-03-16 19:08:25,155|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2023-03-16 19:08:25 2023-03-16 19:08:25,156|Instance2InstanceThread-39|acestream.APIServer|run: ready to receive remote commands on 62062
2023-03-16 19:08:30 Exception in thread ZeroconfThread-30:
2023-03-16 19:08:30 Traceback (most recent call last):
2023-03-16 19:08:30   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2023-03-16 19:08:30     self.run()
2023-03-16 19:08:30   File "ACEStream/third_party/zeroconf/zeroconf.py", line 849, in run
2023-03-16 19:08:30   File "ACEStream/third_party/zeroconf/zeroconf.py", line 1452, in _periodic_check
2023-03-16 19:08:30 AttributeError: 'Zeroconf' object has no attribute 'last_sockets_check'
2023-03-16 19:08:30 `

**Comment by blaise-io** [comment] 2023-04-15 08:16
Please try 2.0.4, it explicitly pulls the amd64 image now, which should work with Docker's Rosetta support.

**Comment by TP18** [comment] 2023-04-15 08:59
Downloaded 2.0.4 somehow the new docker image does not download. Ace Link keeps spinning on menu bar. not sure what to do. When I downgrade to 2.0.2 I can open stream normally. Do I need to delete 2.0.2 docker image?

<img width="991" alt="image" src="https://user-images.githubusercontent.com/4549065/232202661-793b2e9d-d841-4029-ac1e-1e39ae6d2e2a.png">

**Comment by Smultie** [comment] 2023-04-16 13:26
Same issue where 2.0.4 keeps spinning

**Comment by blaise-io** [comment] 2023-04-16 14:29
I'll check Monday when I can access an Apple Silicon machine. For now you can use 2.0.2. You don't need to delete old Ace Link Docker images, they're isolated by version number.

**Comment by Smultie** [comment] 2023-04-16 14:41
Thanks @blaise-io

**Closed** 2023-04-22 08:01 UTC
Labels: bug

**Comment by fredykanute** [comment] 2023-06-21 19:33
I have the same problem.
The docker´s link blaseio/acestream doesn't work in Dockers due to AMD64 issues. I have 4.20.1 Docker versions, 2.0.5 Acelink versions and unchecked Rosetta AMD64 emulation on Apple Silicon
Thanks
