### ISSUE TITLE
Provide version for older OSX please

### ISSUE THREAD

**Issue by ashibhuvan** [blaise-io/acelink#9] opened 2019-02-27 20:16 UTC
Please provide version for this that works for OSX for under 10.13.

**Comment by blaise-io** [comment] 2019-04-19 09:55
I think https://github.com/blaise-io/acelink/releases/tag/1.0.1 works on older versions, can you check?

**Comment by blaise-io** [comment] 2019-11-09 13:39
Duplicate of https://github.com/blaise-io/acelink/issues/4

**Closed by blaise-io** 2019-11-09 13:39 UTC
